# -*- coding: utf-8 -*-
# Content data for Ziyi "Zoe" Wang's personal site. Extracted from zoe-wang.com, Google Scholar, arXiv.

ME = "Ziyi Wang"

PROFILE = {
    "name": "Ziyi ‘Zoe’ Wang",
    "name_cn": "王子一",
    "role": "Ph.D. student in Computer Science & Engineering, Texas A&M University",
    "advisor": {"name": "Prof. Meng Xia", "url": "https://www.xiameng.org/"},
    "email": "ziyiwang@tamu.edu",
    "links": {
        "scholar": "https://scholar.google.com/citations?user=dYNpjEUAAAAJ&hl=en",
        "linkedin": "https://www.linkedin.com/in/ziyi-wang-488122292/",
        "twitter": "https://x.com/ZoeWang0213",
        "github": "https://github.com/Zoewang0213",
    },
    "people": {
        "Dr. Zijian Ding": "https://jason-ding.com/",
        "Prof. Fumeng Yang": "https://www.fmyang.com/",
        "Prof. Yue Zhao": "https://viterbi-web.usc.edu/~yzhao010/",
        "Prof. Xiyang Hu": "https://xiyanghu.github.io/",
        "Prof. Xiang Yan": "https://jacobyan0.github.io/",
        "Prof. Meng Xia": "https://www.xiameng.org/",
    },
}

# ---------------------------------------------------------------- NEWS
# (date, html text). Keep newest first.
NEWS = [
    ("Aug 2026", 'Our paper “Do Vision–Language Models Understand Human Engagement in Games?” has been accepted to <b>EMNLP 2026</b>! See our <a href="https://arxiv.org/abs/2603.18480">preprint</a>.'),
    ("Aug 2026", 'Our new paper “Physics-Preserving Latent Compression” has been accepted to <b>ICDM 2026</b>! It’s a physics-preserving latent compressor for 3D turbulence with zero-shot resolution transfer. See our <a href="https://arxiv.org/abs/2606.21781">preprint</a>.'),
    ("Jun 2026", 'Our new paper “Made to Feel” has been accepted to <b>IEEE VIS 2026</b>! It’s an interview study of how designers bring emotions into affective visualization. See our <a href="https://arxiv.org/abs/2607.01593">preprint</a>.'),
    ("May 2026", 'Our survey paper on a unified view of learning PDEs has been accepted to <b>IJCAI 2026</b>! See our <a href="https://arxiv.org/abs/2601.14517">preprint</a>.'),
    ("Apr 2026", 'Our paper on multimodal ranking attacks against vision–language-model-based product search has been accepted to the <b>ACL 2026 KnowFM Workshop</b>! See our <a href="https://arxiv.org/abs/2601.12263">preprint</a>.'),
    ("Mar 2026", 'We have a new paper examining whether vision–language models can infer human engagement from gameplay video. See our <a href="https://arxiv.org/abs/2603.18480">preprint</a>.'),
    ("Mar 2026", 'Our new paper “StreetDesignAI” has been accepted to <b>DIS 2026</b>! It’s a persona-based multi-agent system that surfaces experiential conflicts in cycling infrastructure design and supports inclusive, trade-off-aware decision making. See our <a href="https://arxiv.org/abs/2601.15671">preprint</a>.'),
    ("Jan 2026", 'We have a new survey systematically reviewing 1,493 papers on human–AI decision-making, proposing unified taxonomies of AI and human roles. See our <a href="https://hal.science/hal-05499178/document">preprint</a>.'),
    ("Jan 2026", 'We have a new paper “Persona-aware and Explainable Bikeability Assessment” on persona-conditioned vision–language models for explainable bikeability prediction. See our <a href="https://arxiv.org/abs/2601.03534">preprint</a>.'),
    ("Jan 2026", 'We have a new paper introducing ResearchCube, a multi-dimensional trade-off exploration system for research ideation. See our <a href="https://arxiv.org/abs/2604.11538">preprint</a>.'),
    ("Nov 2025", 'Our paper on mitigating hallucinations in LLMs using causal reasoning has been accepted to <b>AAAI 2026</b>! See our <a href="https://arxiv.org/abs/2508.12495">preprint</a>.'),
    ("Oct 2025", 'Our new paper “From Image Generation to Infrastructure Design” has been accepted to the <b>NeurIPS 2025 UrbanAI Workshop</b>! It’s a multi-agent pipeline for realistic street-design generation. See our <a href="https://arxiv.org/abs/2509.05469">preprint</a>.'),
    ("Sep 2025", 'We have a new paper introducing CareerPooler, a generative-AI-powered pool-table metaphor system for career exploration that improves engagement, satisfaction, and clarity compared to chatbot baselines. See our <a href="https://arxiv.org/abs/2509.11461">preprint</a>.'),
    ("Jul 2025", 'Our new paper “Frontend Diffusion” has been accepted to <b>IEEE VL/HCC 2025</b>! It’s a multi-stage AI system that turns sketches into website code for junior researchers and designers. See our <a href="https://arxiv.org/abs/2502.03788">preprint</a>.'),
    ("Jul 2025", 'Our new paper “JailDAM” has been accepted to <b>COLM 2025</b>! It proposes an adaptive memory approach for jailbreak detection in vision-language models. See the <a href="https://arxiv.org/abs/2504.03770">preprint</a>.'),
    ("Jun 2025", 'We have a new paper accepted to <b>ECML PKDD 2025</b> on leveraging LLMs for few-shot graph OOD detection. See our <a href="https://arxiv.org/abs/2503.22097">preprint</a>.'),
    ("May 2025", 'We have a new paper on zero-shot graph OOD detection using foundation models (GLIP-OOD). See our <a href="https://arxiv.org/abs/2504.21186">preprint</a>.'),
    ("May 2025", 'We have a new paper introducing GOE-LLM, a framework using LLMs to generate synthetic OOD nodes for graph OOD detection without requiring real OOD data. See our <a href="https://arxiv.org/abs/2504.21198">preprint</a>.'),
]

# ---------------------------------------------------------------- PUBLICATIONS
# authors: list of names; suffix "*" = equal contribution, "†" = corresponding author.
# tags: "first" (first / co-first author), "selected" (highlight on the Selected tab)
# area: "hci" | "ml" | "science"  (used for filter tabs)
PUBS = [
    {
        "id": "vlm-engagement",
        "title": "Do Vision Language Models Understand Human Engagement in Games?",
        "authors": ["Ziyi Wang*", "Qizan Guo*", "Rishitosh Singh*", "Xiyang Hu†"],
        "venue": "EMNLP 2026", "venue_full": "Conference on Empirical Methods in Natural Language Processing", "year": 2026,
        "tags": ["first", "selected"], "area": "hci",
        "image": "vlm-engagement.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2603.18480", "arXiv": "https://arxiv.org/abs/2603.18480"},
        "abstract": "Inferring human engagement from gameplay video is important for game design and player-experience research, yet it remains unclear whether vision–language models (VLMs) can infer such latent psychological states from visual cues alone. Using the GameVibe Few-Shot dataset across nine first-person shooter games, we evaluate three VLMs under six prompting strategies, including zero-shot prediction, theory-guided prompts grounded in Flow, GameFlow, Self-Determination Theory, and MDA, and retrieval-augmented prompting. We consider both pointwise engagement prediction and pairwise prediction of engagement change between consecutive windows. Results show that zero-shot VLM predictions are generally weak and often fail to outperform simple per-game majority-class baselines. Memory- or retrieval-augmented prompting improves pointwise prediction in some settings, whereas pairwise prediction remains consistently difficult across strategies. Theory-guided prompting alone does not reliably help and can instead reinforce surface-level shortcuts. These findings suggest a perception–understanding gap in current VLMs: although they can recognize visible gameplay cues, they still struggle to robustly infer human engagement across games.",
    },
    {
        "id": "streetdesignai",
        "title": "StreetDesignAI: Broadening Designer Perspectives Through Multi-Persona Evaluation of Cycling Infrastructure",
        "authors": ["Ziyi Wang*", "Yilong Dai*", "Duanya Lyu", "Mateo Nader", "Sihan Chen", "Wanghao Ye", "Zijian Ding", "Xiang Yan†"],
        "venue": "DIS 2026", "venue_full": "ACM Designing Interactive Systems Conference", "year": 2026,
        "tags": ["first", "selected"], "area": "hci",
        "image": "streetdesignai.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2601.15671", "arXiv": "https://arxiv.org/abs/2601.15671", "Video": "https://drive.google.com/file/d/1ILckkzmCNqgRDFxUycu3HSWg9ct5IPx1/view?usp=drive_link"},
        "abstract": "Designing inclusive cycling infrastructure requires balancing competing needs of diverse user groups, yet designers often struggle to anticipate how different cyclists experience the same street. We investigate how persona-based multi-agent evaluation can support inclusive design by making experiential conflicts explicit. We present StreetDesignAI, an interactive system that enables designers to (1) ground evaluation in street context through imagery and map data, (2) receive parallel feedback from cyclist personas spanning confident to cautious users, and (3) iteratively modify designs while surfacing conflicts across perspectives. A within-subjects study with 26 transportation professionals demonstrates that structured multi-perspective feedback significantly improves designers' understanding of diverse user perspectives, ability to identify persona needs, and confidence in translating them into design decisions, with higher satisfaction and stronger intention for professional adoption. Qualitative findings reveal how conflict surfacing transforms design exploration from single-perspective optimization toward deliberate trade-off reasoning. We discuss implications for AI tools that scaffold inclusive design through disagreement as an interaction primitive.",
    },
    {
        "id": "careerpooler",
        "title": "CareerPooler: AI-Powered Metaphorical Pool Simulation Improves Experience and Outcomes in Career Exploration",
        "authors": ["Ziyi Wang", "Ziwen Zeng", "Yuan Li", "Zijian Ding†"],
        "venue": "arXiv 2025", "venue_full": "arXiv preprint", "year": 2025,
        "tags": ["first", "selected"], "area": "hci",
        "image": "careerpooler.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2509.11461", "arXiv": "https://arxiv.org/abs/2509.11461", "Video": "https://drive.google.com/file/d/14nSX1ZGgCBLzg_B7leuH9zPsuEBEkmMA/view?usp=sharing"},
        "abstract": "Career exploration is uncertain, requiring decisions with limited information and unpredictable outcomes. While generative AI offers new opportunities for career guidance, most systems rely on linear chat interfaces that produce overly comprehensive and idealized suggestions, overlooking the non-linear and effortful nature of real-world trajectories. We present CareerPooler, a generative AI-powered system that employs a pool-table metaphor to simulate career development as a spatial and narrative interaction. Users strike balls representing milestones, skills, and random events, where hints, collisions, and rebounds embody decision-making under uncertainty. In a within-subjects study with 24 participants, CareerPooler significantly improved engagement, satisfaction, and career clarity compared to a chatbot baseline. Qualitative findings show that spatial-narrative interaction fosters experience-based learning, resilience through setbacks, and reduced psychological burden. Our findings contribute to the design of AI-assisted career exploration systems and more broadly suggest that visually grounded analogical interactions can make generative systems engaging and satisfying.",
    },
    {
        "id": "bikeability",
        "title": "Persona-aware and Explainable Bikeability Assessment: A Vision-Language Model Approach",
        "authors": ["Yilong Dai*", "Ziyi Wang*", "Chenguang Wang", "Kexin Zhou", "Yiheng Qian", "Susu Xu", "Xiang Yan†"],
        "venue": "arXiv 2026", "venue_full": "arXiv preprint", "year": 2026,
        "tags": ["first", "selected"], "area": "ml",
        "image": "bikeability.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2601.03534", "arXiv": "https://arxiv.org/abs/2601.03534"},
        "abstract": "Bikeability assessment is essential for advancing sustainable urban transportation and creating cyclist-friendly cities, and it requires incorporating users' perceptions of safety and comfort. Yet existing perception-based bikeability assessment approaches face key limitations in capturing the complexity of road environments and adequately accounting for heterogeneity in subjective user perceptions. This paper proposes a persona-aware Vision-Language Model framework for bikeability assessment with three novel contributions: (i) theory-grounded persona conditioning based on established cyclist typology that generates persona-specific explanations via chain-of-thought reasoning; (ii) multi-granularity supervised fine-tuning that combines scarce expert-annotated reasoning with abundant user ratings for joint prediction and explainable assessment; and (iii) AI-enabled data augmentation that creates controlled paired data to isolate infrastructure variable impacts. To test and validate this framework, we developed a panoramic image-based crowdsourcing system and collected 12,400 persona-conditioned assessments from 427 cyclists. Experiment results show that the proposed framework offers competitive bikeability rating prediction while uniquely enabling explainable factor attribution.",
    },
    {
        "id": "made-to-feel",
        "title": "Made to Feel: How Designers Bring Emotions into Affective Visualization",
        "authors": ["Yixin Bai", "Ziyi Wang", "Keke Wu", "Fumeng Yang†"],
        "venue": "IEEE VIS 2026", "venue_full": "IEEE Visualization Conference (Short Paper)", "year": 2026,
        "tags": ["selected"], "area": "hci",
        "image": "made-to-feel.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2607.01593", "arXiv": "https://arxiv.org/abs/2607.01593"},
        "abstract": "Affective visualization is increasingly studied in visualization research, yet how designers bring emotions into their visualization work remains unexplored. This paper addresses this gap through semi-structured interviews with 15 visualization practitioners. Using hybrid thematic analysis, we identify: (1) three functions that emotions can serve for viewers (entry, engagement, outcome); (2) three facets of how designers work with emotion (data, design, audience), along with design strategies; and (3) ethical considerations in the design process. We also observe that affective intent often emerges during the design process rather than being planned from the outset, and that emotional impact arises from accumulated design choices rather than isolated visual elements. Finally, we highlight evaluation as a key challenge identified by our participants.",
    },
    {
        "id": "pplc",
        "title": "Physics-Preserving Latent Compression for Zero-Shot Resolution Transfer in 3D Turbulence",
        "authors": ["Yilong Dai", "Yiming Sun", "Yiheng Chen", "Ziyi Wang", "Shengyu Chen", "Xiaowei Jia", "Runlong Yu†"],
        "venue": "ICDM 2026", "venue_full": "IEEE International Conference on Data Mining", "year": 2026,
        "tags": [], "area": "science",
        "image": "pplc.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2606.21781", "arXiv": "https://arxiv.org/abs/2606.21781"},
        "abstract": "High-resolution turbulence modeling is essential for scientific computing, but remains constrained by the cost of direct numerical simulation and the scarcity of full-resolution data. Existing scientific compressors reduce storage but typically operate on per-frame representations, whereas learned compressors yield compact latents that are often resolution-dependent and weakly aligned with the physics of turbulence. This raises the need for a compression framework that reduces data size, preserves physical diagnostics, and transfers from low-resolution training fields to high-resolution test fields without retraining. In this paper, we propose Physics-Preserving Latent Compression (PPLC), a patch-local latent compressor for three-dimensional turbulence. Motivated by inertial-range scale similarity, PPLC treats fixed-size patches as transferable units and applies a shared variational autoencoder independently of the global grid size. It combines exact mean preservation, zero-mean fluctuation encoding, an invertible Haar wavelet front-end, shift-consistency regularization, and overlap-aware reconstruction. Instantiated on forced isotropic turbulence, PPLC is trained only on stride-downsampled 256³ fields and transfers zero-shot to 1024³ fields. Experiments show that PPLC improves the balance between reconstruction accuracy and physical fidelity over classical and learned baselines, keeping diagnostics such as dissipation, enstrophy, energy spectra, and incompressibility closer to the ground truth.",
    },
    {
        "id": "pde-solvers",
        "title": "Learning PDE Solvers with Physics and Data: A Unifying View of Physics-Informed Neural Networks and Neural Operators",
        "authors": ["Yilong Dai", "Shengyu Chen", "Ziyi Wang", "Xiaowei Jia", "Yiqun Xie", "Vipin Kumar", "Runlong Yu†"],
        "venue": "IJCAI 2026", "venue_full": "International Joint Conference on Artificial Intelligence (Survey Track)", "year": 2026,
        "tags": [], "area": "science",
        "image": "pde-solvers.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2601.14517", "arXiv": "https://arxiv.org/abs/2601.14517"},
        "abstract": "Partial differential equations (PDEs) are central to scientific modeling. Modern workflows increasingly rely on learning-based components to support model reuse, inference, and integration across large computational processes. Despite the emergence of various physics-aware data-driven approaches, the field still lacks a unified perspective to uncover their relationships, limitations, and appropriate roles in scientific workflows. To this end, we propose a unifying perspective to place two dominant paradigms: Physics-Informed Neural Networks (PINNs) and Neural Operators (NOs), within a shared design space. We organize existing methods from three fundamental dimensions: what is learned, how physical structures are integrated into the learning process, and how the computational load is amortized across problem instances. In this way, many challenges can be best understood as consequences of these structural properties of learning PDEs. By analyzing advances through this unifying view, our survey aims to facilitate the development of reliable learning-based PDE solvers and catalyze a synthesis of physics and data.",
    },
    {
        "id": "researchcube",
        "title": "ResearchCube: Multi-Dimensional Trade-off Exploration for Research Ideation",
        "authors": ["Zijian Ding", "Fenghai Li", "Ziyi Wang", "Joel Chan†"],
        "venue": "arXiv 2026", "venue_full": "arXiv preprint", "year": 2026,
        "tags": ["selected"], "area": "hci",
        "image": "researchcube.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2604.11538", "arXiv": "https://arxiv.org/abs/2604.11538"},
        "abstract": "Research ideation requires navigating trade-offs across multiple evaluative dimensions—yet most AI-assisted research ideation tools present a missed opportunity: none explicitly design for shared human-AI exploration of multi-dimensional trade-off spaces. This paper presents ResearchCube, a multi-dimensional trade-off exploration system that renders research ideas as manipulable nodes along user-selected bipolar dimensions (e.g., theory-driven vs. data-driven). Rather than unipolar scales where “more is better,” ResearchCube frames each axis as a trade-off spectrum with meaningful poles at both ends, making tensions in research choices explicit. To address the cold-start problem, the system proposes candidate dimension pairs from which users select up to three to construct a personalized 3D evaluation space. Four primary interactions—dimension generation, spatial navigation, drag-based steering, and idea combination—enable researchers to explore, compare, and refine ideas through direct spatial manipulation rather than textual prompts.",
    },
    {
        "id": "sovereign-os",
        "title": "Sovereign-OS: A Charter-Governed Operating System for Autonomous AI Agents with Verifiable Fiscal Discipline",
        "authors": ["Aojie Yuan", "Haiyue Zhang", "Ziyi Wang", "Yue Zhao†"],
        "venue": "arXiv 2026", "venue_full": "arXiv preprint (demo paper)", "year": 2026,
        "tags": [], "area": "ml",
        "image": "sovereign-os.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2603.14011", "arXiv": "https://arxiv.org/abs/2603.14011", "Code": "https://github.com/Justin0504/Sovereign-OS", "Demo": "https://youtu.be/vOarAI_epb4"},
        "abstract": "As AI agents evolve from text generators into autonomous economic actors that accept jobs, manage budgets, and delegate to sub-agents, the absence of runtime governance becomes a critical gap. Existing frameworks orchestrate agent behavior but impose no fiscal constraints, require no earned permissions, and offer no tamper-evident audit trail. We introduce Sovereign-OS, a governance-first operating system that places every agent action under constitutional control. A declarative Charter (YAML) defines mission scope, fiscal boundaries, and success criteria. A CEO (Strategist) decomposes goals into dependency-aware task DAGs; a CFO (Treasury) gates each expenditure against budget caps, daily burn limits, and profitability floors via an auction-based bidding engine; Workers operate under earned-autonomy permissions governed by a dynamic TrustScore; and an Auditor (ReviewEngine) verifies outputs against Charter KPIs, sealing each report with a SHA-256 proof hash. Across our evaluation suite, Sovereign-OS blocks 100% of fiscal violations (30 scenarios), achieves 94% correct permission gating (200 trust-escalation missions), and maintains zero integrity failure over 1,200+ audit reports.",
    },
    {
        "id": "multimodal-geo",
        "title": "Multimodal Generative Engine Optimization: Rank Manipulation for Vision–Language Model Rankers",
        "authors": ["Yixuan Du", "Chenxiao Yu", "Haoyan Xu", "Ziyi Wang", "Yue Zhao", "Xiyang Hu†"],
        "venue": "ACL 2026 KnowFM Workshop", "venue_full": "Workshop on Towards Knowledgeable Foundation Models at ACL 2026", "year": 2026,
        "tags": [], "area": "ml",
        "image": "multimodal-geo.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2601.12263", "arXiv": "https://arxiv.org/abs/2601.12263"},
        "abstract": "Vision-Language Models (VLMs) are rapidly replacing unimodal encoders in modern retrieval and recommendation systems. While their capabilities are well-documented, their robustness against adversarial manipulation in competitive ranking scenarios remains largely unexplored. In this paper, we uncover a critical vulnerability in VLM-based product search: multimodal ranking attacks. We present a novel adversarial framework that enables a malicious actor to unfairly promote a target product by jointly optimizing imperceptible image perturbations and fluent textual suffixes. Unlike existing attacks that treat modalities in isolation, our method employs an alternating gradient-based optimization strategy to exploit the deep cross-modal coupling within the VLM. Extensive experiments on real-world datasets using state-of-the-art models demonstrate that our coordinated attack significantly outperforms text-only and image-only baselines. These findings reveal that multimodal synergy, typically a strength of VLMs, can be weaponized to compromise the integrity of search rankings without triggering conventional content filters.",
    },
    {
        "id": "haid-review",
        "title": "In the Shadow of Judgment: Mapping Out the Landscape of Human–AI Decision-Making Through a Systematic Review",
        "authors": ["Yixin Bai", "Taehyun Yang", "Zhongzheng Xu", "Dayeon Ki", "Ziyi Wang", "Yu Hou", "Fumeng Yang†"],
        "venue": "Preprint 2026", "venue_full": "HAL preprint", "year": 2026,
        "tags": [], "area": "hci",
        "image": "haid-review.jpg",
        "links": {"PDF": "https://hal.science/hal-05499178/document", "HAL": "https://hal.science/hal-05499178/"},
        "abstract": "Research on human–AI decision-making (HAID) has grown rapidly across domains. However, the literature on this topic remains fragmented, and conceptual ambiguities hinder systematic synthesis and cross-domain comparison. We present a systematic review of HAID publications from 2016 to 2024. Starting with 269,060 records collected from 20 publishers and databases, we conducted 5 rounds of relevance and quality screening, and ultimately analyzed 1,493 articles in breadth and depth. We contribute: (1) a systematic categorization of the literature, including 6 contribution types, 13 domains of application, and 4 decision levels; (2) taxonomies of 8 AI roles and 6 human roles, their inputs to decision-making, and their influences on each other; and (3) the identification of 4 research gaps and pathways forward. Our efforts unify scattered work into a coherent framework, strengthen the descriptive and rhetorical power of this field, and lay the groundwork for future research and policy development.",
    },
    {
        "id": "llm-good",
        "title": "Few-Shot Graph Out-of-Distribution Detection with LLMs",
        "authors": ["Haoyan Xu*", "Zhengtao Yao*", "Yushun Dong", "Ziyi Wang", "Ryan A. Rossi", "Mengyuan Li", "Yue Zhao†"],
        "venue": "ECML PKDD 2025", "venue_full": "European Conference on Machine Learning and Principles and Practice of Knowledge Discovery in Databases", "year": 2025,
        "tags": [], "area": "ml",
        "image": "llm-good.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2503.22097", "arXiv": "https://arxiv.org/abs/2503.22097"},
        "abstract": "Existing methods for graph out-of-distribution (OOD) detection typically depend on training graph neural network (GNN) classifiers using a substantial amount of labeled in-distribution (ID) data. However, acquiring high-quality labeled nodes in text-attributed graphs (TAGs) is challenging and costly due to their complex textual and structural characteristics. Large language models (LLMs), known for their powerful zero-shot capabilities in textual tasks, show promise but struggle to naturally capture the critical structural information inherent to TAGs, limiting their direct effectiveness. To address these challenges, we propose LLM-GOOD, a general framework that effectively combines the strengths of LLMs and GNNs to enhance data efficiency in graph OOD detection. We first leverage LLMs' strong zero-shot capabilities to filter out likely OOD nodes, significantly reducing the human annotation burden. To minimize the usage and cost of the LLM, we employ it only to annotate a small subset of unlabeled nodes. We then train a lightweight GNN filter using these noisy labels, enabling efficient predictions of ID status for all other unlabeled nodes. Extensive experiments on four real-world TAG datasets demonstrate that LLM-GOOD significantly reduces human annotation costs and outperforms state-of-the-art baselines in terms of both ID classification accuracy and OOD detection performance.",
    },
    {
        "id": "frontend-diffusion",
        "title": "Frontend Diffusion: Empowering Self-Representation of Junior Researchers and Designers Through Multi-agent System",
        "authors": ["Zijian Ding", "Qinshi Zhang", "Mohan Chi", "Ziyi Wang"],
        "venue": "IEEE VL/HCC 2025", "venue_full": "IEEE Symposium on Visual Languages and Human-Centric Computing", "year": 2025,
        "tags": ["selected"], "area": "hci",
        "image": "frontend-diffusion.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2502.03788", "arXiv": "https://arxiv.org/abs/2502.03788", "Code": "https://github.com/Carolzhangzz/frontendiffusion", "Video": "https://drive.google.com/file/d/16wFXzYiTz8jcXv9L99nEpVOGeoRihFjR/view"},
        "abstract": "With the continuous development of generative AI's logical reasoning abilities, AI's growing code-generation potential poses challenges for both technical and creative professionals. But how can these advances be directed toward empowering junior researchers and designers who often require additional help to build and express their professional and personal identities? We present Frontend Diffusion, a multi-stage agentic system, transforms user-drawn layouts and textual prompts into refined website code, thereby supporting self-representation goals. A user study with 13 junior researchers and designers shows AI as a human capability enhancer rather than a replacement, and highlights the importance of bidirectional human-AI alignment. We then discuss future work such as leveraging AI for career development and fostering bidirectional human-AI alignment on the intent level.",
    },
    {
        "id": "cdcr-sft",
        "title": "Mitigating Hallucinations in Large Language Models via Causal Reasoning",
        "authors": ["Yuangang Li*", "Yiqing Shen*", "Yi Nian", "Jiechao Gao", "Ziyi Wang", "Chenxiao Yu", "Shawn Li", "Jie Wang", "Xiyang Hu", "Yue Zhao†"],
        "venue": "AAAI 2026", "venue_full": "AAAI Conference on Artificial Intelligence", "year": 2026,
        "tags": [], "area": "ml",
        "image": "cdcr-sft.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2508.12495", "arXiv": "https://arxiv.org/abs/2508.12495"},
        "abstract": "Large language models (LLMs) exhibit logically inconsistent hallucinations that appear coherent yet violate reasoning principles, with recent research suggesting an inverse relationship between causal reasoning capabilities and such hallucinations. However, existing reasoning approaches in LLMs, such as Chain-of-Thought (CoT) and its graph-based variants, operate at the linguistic token level rather than modeling the underlying causal relationships between variables, lacking the ability to represent conditional independencies or satisfy causal identification assumptions. To bridge this gap, we introduce causal-DAG construction and reasoning (CDCR-SFT), a supervised fine-tuning framework that trains LLMs to explicitly construct variable-level directed acyclic graph (DAG) and then perform reasoning over it. Moreover, we present a dataset comprising 25,368 samples (CausalDR), where each sample includes an input question, explicit causal DAG, graph-based reasoning trace, and validated answer. Experiments on four LLMs across eight tasks show that CDCR-SFT improves the causal reasoning capability with the state-of-the-art 95.33% accuracy on CLADDER (surpassing human performance of 94.8% for the first time) and reduces the hallucination on HaluEval with 10% improvements.",
    },
    {
        "id": "jaildam",
        "title": "JailDAM: Jailbreak Detection with Adaptive Memory for Vision-Language Model",
        "authors": ["Yi Nian*", "Shenzhe Zhu*", "Yuehan Qin", "Li Li", "Ziyi Wang", "Chaowei Xiao", "Yue Zhao†"],
        "venue": "COLM 2025", "venue_full": "Conference on Language Modeling", "year": 2025,
        "tags": ["selected"], "area": "ml",
        "image": "jaildam.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2504.03770", "arXiv": "https://arxiv.org/abs/2504.03770", "Code": "https://github.com/ShenzheZhu/JailDAM", "Dataset": "https://huggingface.co/datasets/Chouoftears/JailDAM-data"},
        "abstract": "Multimodal large language models (MLLMs) excel in vision-language tasks but also pose significant risks of generating harmful content, particularly through jailbreak attacks. Jailbreak attacks refer to intentional manipulations that bypass safety mechanisms in models, leading to the generation of inappropriate or unsafe content. Detecting such attacks is critical to ensuring the responsible deployment of MLLMs. Existing jailbreak detection methods face three primary challenges: (1) Many rely on model hidden states or gradients, limiting their applicability to white-box models; (2) They involve high computational overhead from uncertainty-based analysis, which limits real-time detection; and (3) They require fully labeled harmful datasets, which are often scarce in real-world settings. To address these issues, we introduce a test-time adaptive framework called JailDAM. Our method leverages a memory-based approach guided by policy-driven unsafe knowledge representations, eliminating the need for explicit exposure to harmful data. By dynamically updating unsafe knowledge during test-time, our framework improves generalization to unseen jailbreak strategies while maintaining efficiency. Experiments on multiple VLM jailbreak benchmarks demonstrate that JailDAM delivers state-of-the-art performance in harmful content detection, improving both accuracy and speed.",
    },
    {
        "id": "street-design-gen",
        "title": "From Image Generation to Infrastructure Design: A Multi-agent Pipeline for Street Design Generation",
        "authors": ["Chenguang Wang", "Xiang Yan", "Yilong Dai", "Ziyi Wang", "Susu Xu†"],
        "venue": "NeurIPS 2025 UrbanAI Workshop", "venue_full": "NeurIPS 2025 Workshop on Urban AI", "year": 2025,
        "tags": [], "area": "ml",
        "image": "street-design-gen.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2509.05469", "arXiv": "https://arxiv.org/abs/2509.05469"},
        "abstract": "Realistic visual renderings of street-design scenarios are essential for public engagement in active transportation planning. Traditional approaches are labor-intensive, hindering collective deliberation and collaborative decision-making. While AI-assisted generative design shows transformative potential by enabling rapid creation of design scenarios, existing generative approaches typically require large amounts of domain-specific training data and struggle to enable precise spatial variations of design/configuration in complex street-view scenes. We introduce a multi-agent system that edits and redesigns bicycle facilities directly on real-world street-view imagery. The framework integrates lane localization, prompt optimization, design generation, and automated evaluation to synthesize realistic, contextually appropriate designs. Experiments across diverse urban scenarios demonstrate that the system can adapt to varying road geometries and environmental conditions, consistently yielding visually coherent and instruction-compliant results.",
    },
    {
        "id": "goe-llm",
        "title": "Graph Synthetic Out-of-Distribution Exposure with Large Language Models",
        "authors": ["Haoyan Xu*", "Zhengtao Yao*", "Ziyi Wang", "Zhan Cheng", "Xiyang Hu", "Mengyuan Li", "Yue Zhao†"],
        "venue": "arXiv 2025", "venue_full": "arXiv preprint", "year": 2025,
        "tags": [], "area": "ml",
        "image": "goe-llm.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2504.21198", "arXiv": "https://arxiv.org/abs/2504.21198"},
        "abstract": "Out-of-distribution (OOD) detection in graphs is critical for ensuring model robustness in open-world and safety-sensitive applications. Existing approaches to graph OOD detection typically involve training an in-distribution (ID) classifier using only ID data, followed by the application of post-hoc OOD scoring techniques. Although OOD exposure—introducing auxiliary OOD samples during training—has proven to be an effective strategy for enhancing detection performance, current methods in the graph domain generally assume access to a set of real OOD nodes. This assumption, however, is often impractical due to the difficulty and cost of acquiring representative OOD samples. In this paper, we introduce GOE-LLM, a novel framework that leverages Large Language Models (LLMs) for OOD exposure in graph OOD detection without requiring real OOD nodes. GOE-LLM introduces two pipelines: (1) identifying pseudo-OOD nodes from the initially unlabeled graph using zero-shot LLM annotations, and (2) generating semantically informative synthetic OOD nodes via LLM-prompted text generation. We evaluate our approach across multiple benchmark datasets, showing that GOE-LLM significantly outperforms state-of-the-art graph OOD detection methods that do not use OOD exposure and achieves comparable performance to those relying on real OOD data.",
    },
    {
        "id": "glip-ood",
        "title": "GLIP-OOD: Zero-Shot Graph OOD Detection with Graph Foundation Model",
        "authors": ["Haoyan Xu*", "Zhengtao Yao*", "Xuzhi Zhang", "Ziyi Wang", "Langzhou He", "Yushun Dong", "Philip S. Yu", "Mengyuan Li", "Yue Zhao†"],
        "venue": "arXiv 2025", "venue_full": "arXiv preprint", "year": 2025,
        "tags": [], "area": "ml",
        "image": "glip-ood.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2504.21186", "arXiv": "https://arxiv.org/abs/2504.21186"},
        "abstract": "Out-of-distribution (OOD) detection is critical for ensuring the safety and reliability of machine learning systems, particularly in dynamic and open-world environments. In the vision and text domains, zero-shot OOD detection—which requires no training on in-distribution (ID) data—has made significant progress through the use of large-scale pretrained models such as vision-language models (VLMs) and large language models (LLMs). However, zero-shot OOD detection in graph-structured data remains largely unexplored. In this work, we take the first step toward enabling zero-shot graph OOD detection by leveraging a graph foundation model (GFM). We show that, when provided only with class label names, the GFM can perform OOD detection without any node-level supervision—outperforming existing supervised methods across multiple datasets. To address the more practical setting where OOD label names are unavailable, we introduce GLIP-OOD, a novel framework that employs LLMs to generate semantically informative pseudo-OOD labels from unlabeled data. Our approach is the first to enable node-level graph OOD detection in a fully zero-shot setting, and achieves state-of-the-art performance on four benchmark text-attributed graph datasets.",
    },
    {
        "id": "cognipair",
        "title": "CogniPair: From LLM Chatbots to Conscious AI Agents — GNWT-Based Multi-Agent Digital Twins for Social Pairing — Dating & Hiring Applications",
        "authors": ["Wanghao Ye", "Sihan Chen", "Yiting Wang", "Shwai He", "Bowei Tian", "Guoheng Sun", "Ziyi Wang", "et al."],
        "venue": "arXiv 2025", "venue_full": "arXiv preprint", "year": 2025,
        "tags": [], "area": "ml",
        "image": "cognipair.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2506.03543", "arXiv": "https://arxiv.org/abs/2506.03543"},
        "abstract": "Current large language model (LLM) agents lack authentic human psychological processes necessary for genuine digital twins and social AI applications. To address this limitation, we present a computational implementation of Global Workspace Theory (GNWT) that integrates human cognitive architecture principles into LLM agents, creating specialized sub-agents for emotion, memory, social norms, planning, and goal-tracking coordinated through a global workspace mechanism. However, authentic digital twins require accurate personality initialization. We therefore develop a novel adventure-based personality test that evaluates true personality through behavioral choices within interactive scenarios, bypassing self-presentation bias found in traditional assessments. Building on these innovations, our CogniPair platform enables digital twins to engage in realistic simulated dating interactions and job interviews before real encounters. Validation using 551 GNWT-Agents and Columbia University Speed Dating dataset demonstrates 72% correlation with human attraction patterns, 77.8% match prediction accuracy, and 74% agreement in human validation studies.",
    },
    {
        "id": "tacgen",
        "title": "TacGen: Touch Is a Necessary Dimension of Physical-World Representation — Addressing Tactile Data Scarcity with Scalable Vision-to-Touch Alignment and Generation",
        "authors": ["Wanghao Ye", "Aarosh Das", "Sihan Chen", "Yiting Wang", "Bowei Tian", "Guoheng Sun", "Shwai He", "Zheyu Shen", "Ziyao Wang", "Yexiao He", "Zhaoyi Liu", "Meng Liu", "Yuning Zhang", "Meng Feng", "Ziyi Wang", "Yilong Dai", "Yifei Dong", "Siyuan Peng", "Zhenle Duan", "Joshua Liu", "Lang Xiong", "Ang Li†"],
        "venue": "arXiv 2026", "venue_full": "arXiv preprint", "year": 2026,
        "tags": [], "area": "ml",
        "image": "tacgen.jpg",
        "links": {"PDF": "https://arxiv.org/pdf/2606.29173", "arXiv": "https://arxiv.org/abs/2606.29173"},
        "abstract": "Touch resolves the physical-property ambiguity left by vision: exploratory contact recovers shape, texture, compliance, and material, and visuo-haptic object representations converge in ventral visual cortex. We ask whether representation learning can reproduce this grounding. TacGen mitigates the tactile-data scarcity bottleneck by combining pre-specified V+T contrastive alignment with a latent-space residual-MLP V→T generator that synthesizes tactile latents from RGB for tactile-data scaling. With matched DINOv2 backbones, splits, and probes, V+T improves matched V-only on mass, density, hardness, and uncertainty-banded force labels. The same representation lifts matched-capacity TACTO manipulation from 0.246 to 0.979 while V-only capacity scaling accounts for only 4.5% of the gap. Across five-seed SSVTP/TVL reproductions, YCB-Sight transfer, three-backbone checks, permutation/random-feature controls, hash-verified manifests, and measured-force validation checks, the evidence supports the claim that touch supplies a necessary physical evidence channel for representations of contact-dependent properties.",
    },
]

# ---------------------------------------------------------------- DESIGN
DESIGN_SECTIONS = [
    {"id": "nio", "title": "Global brand design", "org": "NIO", "count": 10,
     "blurb": "Brand visuals, key art, event identities and product graphics for a global EV brand."},
    {"id": "bmw", "title": "HMI design", "org": "BMW", "count": 7,
     "blurb": "In-car human–machine interface concepts: panoramic vision, head-up display and steering-wheel controls."},
    {"id": "publicis", "title": "UX design", "org": "Publicis Sapient", "count": 8,
     "blurb": "Product and experience design for enterprise clients: flows, design systems and iconography."},
    {"id": "bilibili", "title": "AI product management", "org": "bilibili", "count": 4,
     "blurb": "AI-powered product concepts and prototypes for a large creator community."},
    {"id": "other", "title": "Other", "org": "Side projects & play", "count": 12,
     "blurb": "Illustration, branding experiments, apps and playground work."},
]

SCHOLAR = {"citations": 153, "h_index": 7, "i10_index": 6, "as_of": "Sep 2026"}

# ---------------------------------------------------------------- BACKGROUND
# Sources: LinkedIn (via search snippets / alphaXiv mirror), DreamLab people page, Jason Ding's site.
# TODO(Zoe): verify months, and add your undergraduate degree (not found publicly).
EDUCATION = [
    {"when": "2026 –", "what": "Ph.D., Computer Science & Engineering", "where": "Texas A&M University · advised by Prof. Meng Xia"},
    {"when": "2024 – 2026", "what": "M.S., Human-Computer Interaction (HCIM)", "where": "University of Maryland, College Park · with Dr. Zijian Ding & Prof. Fumeng Yang"},
]
EXPERIENCE = [
    {"when": "2025 –", "what": "Research collaborator", "where": "USC (Prof. Yue Zhao) · ASU (Prof. Xiyang Hu) · UF (Prof. Xiang Yan)"},
    {"when": "2024", "what": "AI Product Manager", "where": "bilibili"},
    {"when": "2023 – 2024", "what": "HMI / UX Designer", "where": "BMW Group"},
    {"when": "2023", "what": "UX Designer", "where": "Publicis Sapient"},
    {"when": "2023", "what": "Global Brand Designer", "where": "NIO"},
]
